version: '3.7'
services:
  app:
    container_name: aquahub_app
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    environment:
      - APP_ENV=staging
      - APP_DEBUG=false
      - VITE_POCKETBASE_URL=
      - VITE_REDIRECT_URL=
    volumes:
      - ..:/workspace:cached
      - vendor:/workspace/vendor:cached
      - ${HOME}${USERPROFILE:-}/.ssh:/root/.ssh
      - ${HOME}${USERPROFILE:-}/.gitconfig:/root/.gitconfig
      - ${HOME}${USERPROFILE:-}/.gitignore_global:/root/.gitignore_global
    depends_on: [pocketbase]
    command: sleep infinity

  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    container_name: aquahub_pocketbase
    restart: unless-stopped
    volumes:
      - ./data/db:/pb_data

volumes:
  vendor: null
