version: '3'
services:
  app:
    container_name: aquahub_devcontainer_app
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DATABASE_URL=mysql://root@database/development
    volumes:
      - ..:/workspace:cached
      - vendor:/workspace/vendor:cached
      - ${HOME}${USERPROFILE:-}/.ssh:/root/.ssh
      - ${HOME}${USERPROFILE:-}/.gitconfig:/root/.gitconfig
      - ${HOME}${USERPROFILE:-}/.gitignore_global:/root/.gitignore_global
    depends_on: [database]
    command: sleep infinity

  database:
    container_name: aquahub_devcontainer_db
    image: mariadb:10.9
    environment:
      - TZ=Europe/Zurich
      - MYSQL_ALLOW_EMPTY_PASSWORD='yes'
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=development
      - MYSQL_USER=root
    ports: ['3333:3306']
    volumes:
      - ./data/db:/var/lib/mysql

volumes:
  vendor: null
