import type { NextPage } from 'next';
import Head from 'next/head';
import Header from '../components/Header';

const Dev: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Aqua App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className="dark:bg-gray">Lol</div>
    </>
  );
};

export default Dev;
